### ISSUE TITLE
Difference Methylation analysis on Regions Of Interesting (ROI)

### ISSUE THREAD

**Issue by ChengYunazhi** [hhg7/defiant#1] opened 2018-03-26 14:24 UTC
Hi, 

    can defiant analysis Difference Methylation on ROI？For example, I want to analysis difference methylation of a set of immune response genes between two groups,  the difference methylation is on whole genebody level, not DMR. 

Thanks! 

Yuanzhi

**Comment by hhg7** [comment] 2018-03-27 00:44
hi @ChengYunazhi Defiant was designed to identify differentially methylated regions.  However, you can run defiant with the "-E" option to get information about every CpG/CpN site and compare on a whole genebody level as you want.  This will give you a p-value and percent difference for every CpG/CpN site in a file that starts with "nucleotide".  You can compare different regions this way.  You can paste attach the output file here, if you like, and I can help.

**Comment by ChengYunazhi** [comment] 2018-03-27 05:54
Thanks David, I'll try this "-E" option.

**Comment by ChengYunazhi** [comment] 2018-04-01 09:03
Hi, @hhg7 

Is there a statistical method that gives just one p-value for differential methylation of ROIs? I used defiant to get a p-value for ever CpG in ROIs, but how to assess whether there is a significant difference in mean methylation level between the two sample or two groups in these ROIs? A similar analysis can be done in the MEDIP-seq data, I don’t know if this method is feasible in WGBS data?

Thanks

Yuanzhi

**Comment by hhg7** [comment] 2018-04-01 14:51
hi @ChengYunazhi I will write a script to do what you ask, it might be a few days.  It will process the output file from the "-E" option.

**Comment by ChengYunazhi** [comment] 2018-04-02 04:15
Thanks for your kind help, @hhg7 . Is it possible to have the method address datasets with or without biological replicates?

**Comment by hhg7** [comment] 2018-04-02 12:30
hi @ChengYunazhi yes, if there are no biological replicates the program uses Fisher's exact test instead of Welch's t-test.

**Comment by hhg7** [comment] 2018-04-04 02:19
@ChengYunazhi I've uploaded the program roi.c onto the main repository.  Please let me know how it runs.  I look forward to your response.

**Comment by ChengYunazhi** [comment] 2018-04-04 09:14
Thanks @hhg7 ,  I will run it and give you feedback !

**Comment by hhg7** [comment] 2018-04-10 14:49
@ChengYunazhi did the roi program do what you intended? please let me know, I'd like to close the issue.

**Closed as completed** 2018-04-17 17:21 UTC
Labels: help wanted
